import type { NPCSchedule, RecipeDefinition, StoryDefinition } from '@together/shared';


export type ItemDefinition = {
  id: string;
  category: 'grain' | 'lentil' | 'vegetable' | 'fruit' | 'dairy' | 'spice' | 'oil' | 'beverage' | 'bakery' | 'staple' | 'household';
  displayName: string;
  price: number;
  stackSize: number;
  persistence: 'personal' | 'household' | 'world';
  sellValue?: number;
  recipeTags?: readonly string[];
};

export const items: readonly ItemDefinition[] = [
  { id: 'tea', category: 'beverage', displayName: 'Tea Leaves', price: 180, stackSize: 12, persistence: 'household', sellValue: 90, recipeTags: ['chai'] },
  { id: 'coffee', category: 'beverage', displayName: 'Filter Coffee', price: 260, stackSize: 10, persistence: 'household', sellValue: 130, recipeTags: ['coffee'] },
  { id: 'milk', category: 'dairy', displayName: 'Milk', price: 80, stackSize: 8, persistence: 'household', sellValue: 30, recipeTags: ['drink','breakfast'] },
  { id: 'sugar', category: 'staple', displayName: 'Sugar', price: 75, stackSize: 10, persistence: 'household', sellValue: 30, recipeTags: ['sweetener'] },
  { id: 'poha', category: 'grain', displayName: 'Poha', price: 90, stackSize: 10, persistence: 'household', sellValue: 40, recipeTags: ['breakfast'] },
  { id: 'rice', category: 'grain', displayName: 'Rice', price: 130, stackSize: 16, persistence: 'household', sellValue: 60, recipeTags: ['meal'] },
  { id: 'lentils', category: 'lentil', displayName: 'Dal', price: 145, stackSize: 14, persistence: 'household', sellValue: 70, recipeTags: ['meal'] },
  { id: 'onion', category: 'vegetable', displayName: 'Onions', price: 55, stackSize: 12, persistence: 'household', sellValue: 20, recipeTags: ['prep'] },
  { id: 'vegetables', category: 'vegetable', displayName: 'Mixed Vegetables', price: 125, stackSize: 10, persistence: 'household', sellValue: 50, recipeTags: ['meal'] },
  { id: 'spices', category: 'spice', displayName: 'Everyday Masala', price: 150, stackSize: 12, persistence: 'household', sellValue: 75, recipeTags: ['seasoning'] },
  { id: 'oil', category: 'oil', displayName: 'Cooking Oil', price: 170, stackSize: 10, persistence: 'household', sellValue: 80, recipeTags: ['cooking'] },
  { id: 'eggs', category: 'staple', displayName: 'Eggs', price: 110, stackSize: 12, persistence: 'household', sellValue: 45, recipeTags: ['breakfast'] },
  { id: 'bread', category: 'bakery', displayName: 'Bread', price: 65, stackSize: 6, persistence: 'household', sellValue: 25, recipeTags: ['breakfast','snack'] },
  { id: 'tomato', category: 'vegetable', displayName: 'Tomatoes', price: 60, stackSize: 12, persistence: 'household', sellValue: 25, recipeTags: ['prep'] },
  { id: 'potato', category: 'vegetable', displayName: 'Potatoes', price: 70, stackSize: 12, persistence: 'household', sellValue: 30, recipeTags: ['meal'] },
  { id: 'fruit', category: 'fruit', displayName: 'Seasonal Fruit', price: 140, stackSize: 10, persistence: 'household', sellValue: 55, recipeTags: ['snack'] },
  { id: 'biscuits', category: 'bakery', displayName: 'Tea Biscuits', price: 55, stackSize: 8, persistence: 'household', sellValue: 20, recipeTags: ['snack'] },
  { id: 'semolina', category: 'grain', displayName: 'Semolina / Rava', price: 85, stackSize: 10, persistence: 'household', sellValue: 35, recipeTags: ['breakfast'] },
  { id: 'butter', category: 'dairy', displayName: 'Butter', price: 95, stackSize: 8, persistence: 'household', sellValue: 35, recipeTags: ['breakfast','baking'] },
  { id: 'pasta', category: 'grain', displayName: 'Pasta', price: 120, stackSize: 10, persistence: 'household', sellValue: 50, recipeTags: ['meal'] },
  { id: 'noodles', category: 'grain', displayName: 'Noodles', price: 95, stackSize: 10, persistence: 'household', sellValue: 40, recipeTags: ['meal'] },
  { id: 'flour', category: 'grain', displayName: 'Flour', price: 70, stackSize: 12, persistence: 'household', sellValue: 30, recipeTags: ['baking','breakfast'] },
  { id: 'cleaner', category: 'household', displayName: 'Surface Cleaner', price: 120, stackSize: 6, persistence: 'household', sellValue: 45 },
] as const;

export type NamedNpcDefinition = {
  id: string;
  displayName: string;
  role: string;
  homeOrWork: string;
  schedule: NPCSchedule;
  memoryFlags: readonly string[];
};

export type LeisureActivityDefinition = {
  id: string;
  displayName: string;
  district: string;
  locationId: string;
  participants: [number, number];
  requiredCapability?: string;
  memoryTags: readonly string[];
};

export const namedNpcs: readonly NamedNpcDefinition[] = [
  { id: 'roshan', displayName: 'Roshan', role: 'Café owner and barista mentor', homeOrWork: 'lantern_cafe_roshan', schedule: { npcId: 'roshan', periods: [{ start: '06:30', end: '07:00', action: 'open_cafe' }, { start: '07:00', end: '12:00', action: 'work_counter' }, { start: '12:00', end: '13:00', action: 'break_back_table' }, { start: '13:00', end: '21:30', action: 'work_counter' }, { start: '21:30', end: '22:00', action: 'close_cafe' }] }, memoryFlags: ['first_meeting','player_works_here','missed_shift','household_moved'] },
  { id: 'kamla', displayName: 'Kamla Aunty', role: 'Mogra Court caretaker and neighbour', homeOrWork: 'mogra_court', schedule: { npcId: 'kamla', periods: [{ start: '06:30', end: '09:30', action: 'courtyard_morning' }, { start: '09:30', end: '16:30', action: 'caretaker_office' }, { start: '16:30', end: '20:30', action: 'courtyard_evening' }] }, memoryFlags: ['move_in_welcome','helped_repair','household_moved'] },
  { id: 'ravi', displayName: 'Ravi', role: 'Repair-shop owner', homeOrWork: 'rain_tree_repair', schedule: { npcId: 'ravi', periods: [{ start: '09:00', end: '19:30', action: 'repair_shop' }] }, memoryFlags: ['first_meeting','diy_lesson','pipe_help'] },
  { id: 'meera', displayName: 'Meera', role: 'Market grocer', homeOrWork: 'lantern_market', schedule: { npcId: 'meera', periods: [{ start: '06:45', end: '13:00', action: 'market_stall' }, { start: '15:00', end: '20:30', action: 'market_stall' }] }, memoryFlags: ['first_groceries','recipe_hint','festival_ingredients'] },
  { id: 'dev', displayName: 'Dev', role: 'Cycle and scooter rental/repair', homeOrWork: 'bay_cycle_hut', schedule: { npcId: 'dev', periods: [{ start: '08:00', end: '19:00', action: 'cycle_shop' }] }, memoryFlags: ['cycle_intro','scooter_intro','fixed_tire'] },
  { id: 'naina', displayName: 'Naina', role: 'Plant nursery worker', homeOrWork: 'rain_tree_nursery', schedule: { npcId: 'naina', periods: [{ start: '09:00', end: '19:00', action: 'nursery' }] }, memoryFlags: ['plant_adopted','nursery_shift','plant_flowered'] },
  { id: 'arjun', displayName: 'Arjun', role: 'Waterfront rental attendant', homeOrWork: 'bay_kayak_hut', schedule: { npcId: 'arjun', periods: [{ start: '08:00', end: '18:30', action: 'kayak_hut' }] }, memoryFlags: ['safety_intro','first_kayak','storm_closed'] },
  { id: 'isha', displayName: 'Isha', role: 'Community office and library worker', homeOrWork: 'the_common_library', schedule: { npcId: 'isha', periods: [{ start: '09:00', end: '18:00', action: 'library_desk' }] }, memoryFlags: ['community_intro','moving_paperwork','hobby_group'] },
  { id: 'sana', displayName: 'Sana', role: 'Street-food vendor', homeOrWork: 'lantern_food_corner', schedule: { npcId: 'sana', periods: [{ start: '16:00', end: '23:00', action: 'food_stall' }] }, memoryFlags: ['first_snack','late_shift_chai','rain_chat'] },
  { id: 'kabir', displayName: 'Kabir', role: 'Neighbour and recurring friend', homeOrWork: 'mogra_court', schedule: { npcId: 'kabir', periods: [{ start: '07:00', end: '09:00', action: 'neighbourhood' }, { start: '18:00', end: '23:00', action: 'neighbourhood' }] }, memoryFlags: ['new_neighbour','board_game','community_event'] },
  { id: 'leela', displayName: 'Leela', role: 'Long-time Mogra Court resident and balcony gardener', homeOrWork: 'mogra_court', schedule: { npcId: 'leela', periods: [{ start: '06:45', end: '09:00', action: 'balcony_garden' }, { start: '17:00', end: '20:30', action: 'courtyard_chat' }] }, memoryFlags: ['first_meeting','plant_tip','parcel_help','festival_lights'] },
  { id: 'farhan', displayName: 'Farhan', role: 'Library regular and community-event volunteer', homeOrWork: 'the_common_library', schedule: { npcId: 'farhan', periods: [{ start: '10:00', end: '14:00', action: 'library_tables' }, { start: '17:30', end: '21:00', action: 'community_events' }] }, memoryFlags: ['first_meeting','board_game','community_event','moving_help'] },
] as const;


export const npcDialogue: Readonly<Record<string, { greeting: string; weather: string; familiar: string }>> = {
  roshan: { greeting: 'Morning. Sit if you like — the first cup is always calmer before the rush.', weather: 'Rain makes everyone order one more chai than they planned.', familiar: 'You know where the clean cups are now. That makes you almost staff.' },
  kamla: { greeting: 'You are settling in? Good. A home needs time before it starts feeling like yours.', weather: 'Keep the balcony things inside tonight. The wind has opinions.', familiar: 'I noticed the place looks different again. You two are making it your own.' },
  ravi: { greeting: 'If it rattles, leaks, squeaks or leans, bring it here before you throw it away.', weather: 'Monsoon finds every loose screw in the city.', familiar: 'You are getting better with tools. I might have less work because of you.' },
  meera: { greeting: 'Tell me what you are cooking and I will tell you what you forgot.', weather: 'Rainy evening? Take extra ginger. Trust me.', familiar: 'I kept the good tomatoes aside. You come often enough to earn that privilege.' },
  dev: { greeting: 'Cycle first. Scooter later. The city is nicer when you learn its hills slowly.', weather: 'Wet roads are fine if you stop trying to impress anyone.', familiar: 'Your usual cycle is free. I knew you would come by.' },
  naina: { greeting: 'Do not pick the prettiest plant. Pick the one your window can actually keep happy.', weather: 'The plants love this air even if the rest of us are tired of the rain.', familiar: 'That pothos you took home should be putting out a new leaf by now.' },
  arjun: { greeting: 'The bay is calm enough. First time out, stay inside the yellow markers.', weather: 'Not today. The water looks peaceful from here, but the wind is stronger out there.', familiar: 'You know the launch now. I only need to remind you about the life jacket once.' },
  isha: { greeting: 'Library, forms, hobby board — whichever kind of day you are having, we probably have a corner for it.', weather: 'Bad weather turns this place into the city living room.', familiar: 'There is a community notice you might actually like this time.' },
  sana: { greeting: 'You look hungry enough for something hot and not patient enough to cook.', weather: 'Rain makes the oil hiss louder. Best sound on this street.', familiar: 'Same snack as last time, or are we pretending to be adventurous today?' },
  kabir: { greeting: 'Hey. I am nearby most evenings. Knock if you ever need one more person for a game.', weather: 'Perfect weather to cancel a plan and then make a better one indoors.', familiar: 'I brought the cards. I assumed your table was becoming our table again.' },
  leela: { greeting: 'The balcony gets good light before nine. After that, even the plants complain.', weather: 'Move small pots away from the railing before the wind starts showing off.', familiar: 'Your plants are doing well. That means you are probably doing all right too.' },
  farhan: { greeting: 'I was going to work quietly. Then someone put a board game on the community table.', weather: 'Rain gives everyone permission to stay longer than they meant to.', familiar: 'If you are free later, we are trying another game night. No serious rules.' },
} as const;

const basicOutcomes = [
  { id: 'good', maxMistakes: 0, quality: 'good' },
  { id: 'imperfect', minMistakes: 1, maxMistakes: 2, quality: 'imperfect' },
  { id: 'burnt', minMistakes: 3, quality: 'burnt' },
] as const;

export const recipes: readonly RecipeDefinition[] = [
  { id: 'chai', displayName: 'Chai', servings: 2, ingredients: [{ itemId: 'tea', quantity: 1 }, { itemId: 'milk', quantity: 1 }, { itemId: 'sugar', quantity: 1, optional: true }], tools: ['kettle','saucepan','mug'], steps: [{ id: 'measure', action: 'measure', station: 'counter', dependsOn: [], parallelGroup: 'prep' }, { id: 'boil', action: 'boil', station: 'hob', dependsOn: ['measure'] }, { id: 'pour', action: 'pour', station: 'counter', dependsOn: ['boil'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['pour'] }], outcomes: [...basicOutcomes], memoryTags: ['home_ritual','shared_drink'] },
  { id: 'filter_coffee', displayName: 'Filter Coffee', servings: 2, ingredients: [{ itemId: 'coffee', quantity: 1 }, { itemId: 'milk', quantity: 1 }], tools: ['filter','kettle','mug'], steps: [{ id: 'measure', action: 'measure', station: 'counter', dependsOn: [] }, { id: 'boil', action: 'boil', station: 'hob', dependsOn: ['measure'] }, { id: 'pour', action: 'pour', station: 'counter', dependsOn: ['boil'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['pour'] }], outcomes: [...basicOutcomes], memoryTags: ['morning'] },
  { id: 'poha', displayName: 'Poha', servings: 2, ingredients: [{ itemId: 'poha', quantity: 2 }, { itemId: 'onion', quantity: 1 }, { itemId: 'spices', quantity: 1 }], tools: ['pan','knife'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [], parallelGroup: 'prep' }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: [], parallelGroup: 'prep' }, { id: 'fry', action: 'fry', station: 'hob', dependsOn: ['cut'] }, { id: 'stir', action: 'stir', station: 'hob', dependsOn: ['wash','fry'] }, { id: 'plate', action: 'plate', station: 'counter', dependsOn: ['stir'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['plate'] }], outcomes: [...basicOutcomes], memoryTags: ['breakfast','shared_meal'] },
  { id: 'khichdi', displayName: 'Khichdi', servings: 3, ingredients: [{ itemId: 'rice', quantity: 1 }, { itemId: 'lentils', quantity: 1 }, { itemId: 'spices', quantity: 1 }], tools: ['pressure_cooker','bowl'], steps: [{ id: 'wash_rice', action: 'wash', station: 'sink', dependsOn: [], parallelGroup: 'prep' }, { id: 'wash_dal', action: 'wash', station: 'sink', dependsOn: [], parallelGroup: 'prep' }, { id: 'measure', action: 'measure', station: 'counter', dependsOn: [] }, { id: 'boil', action: 'boil', station: 'hob', dependsOn: ['wash_rice','wash_dal','measure'] }, { id: 'stir', action: 'stir', station: 'hob', dependsOn: ['boil'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['comfort_food','rainy_evening'] },
  { id: 'omelette', displayName: 'Omelette', servings: 2, ingredients: [{ itemId: 'eggs', quantity: 3 }, { itemId: 'onion', quantity: 1, optional: true }], tools: ['pan','bowl'], steps: [{ id: 'cut', action: 'cut', station: 'counter', dependsOn: [], parallelGroup: 'prep' }, { id: 'measure', action: 'measure', station: 'counter', dependsOn: [], parallelGroup: 'prep' }, { id: 'fry', action: 'fry', station: 'hob', dependsOn: ['measure'] }, { id: 'plate', action: 'plate', station: 'counter', dependsOn: ['fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['plate'] }], outcomes: [...basicOutcomes], memoryTags: ['breakfast'] },
  { id: 'fried_rice', displayName: 'Fried Rice', servings: 3, ingredients: [{ itemId: 'rice', quantity: 2 }, { itemId: 'vegetables', quantity: 2 }, { itemId: 'oil', quantity: 1 }], tools: ['wok','knife'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [], parallelGroup: 'prep' }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: [], parallelGroup: 'prep' }, { id: 'boil', action: 'boil', station: 'hob_a', dependsOn: ['wash'] }, { id: 'fry', action: 'fry', station: 'hob_b', dependsOn: ['cut'] }, { id: 'stir', action: 'stir', station: 'hob_b', dependsOn: ['boil','fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['shared_meal','parallel_cooking'] },
  { id: 'upma', displayName: 'Upma', servings: 2, ingredients: [{ itemId: 'semolina', quantity: 2 }, { itemId: 'onion', quantity: 1 }, { itemId: 'spices', quantity: 1 }, { itemId: 'oil', quantity: 1 }], tools: ['pan','knife'], steps: [{ id: 'cut', action: 'cut', station: 'counter', dependsOn: [] }, { id: 'fry', action: 'fry', station: 'hob', dependsOn: ['cut'] }, { id: 'measure', action: 'measure', station: 'counter', dependsOn: [] }, { id: 'stir', action: 'stir', station: 'hob', dependsOn: ['fry','measure'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['breakfast'] },
  { id: 'toast', displayName: 'Butter Toast', servings: 2, ingredients: [{ itemId: 'bread', quantity: 2 }, { itemId: 'butter', quantity: 1 }], tools: ['pan'], steps: [{ id: 'fry', action: 'fry', station: 'hob', dependsOn: [] }, { id: 'plate', action: 'plate', station: 'counter', dependsOn: ['fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['plate'] }], outcomes: [...basicOutcomes], memoryTags: ['breakfast','quick_meal'] },
  { id: 'dal', displayName: 'Everyday Dal', servings: 3, ingredients: [{ itemId: 'lentils', quantity: 2 }, { itemId: 'spices', quantity: 1 }, { itemId: 'oil', quantity: 1 }], tools: ['pressure_cooker','pan'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [] }, { id: 'boil', action: 'boil', station: 'hob_a', dependsOn: ['wash'] }, { id: 'fry', action: 'fry', station: 'hob_b', dependsOn: [] }, { id: 'stir', action: 'stir', station: 'hob_a', dependsOn: ['boil','fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['comfort_food','shared_meal'] },
  { id: 'steamed_rice', displayName: 'Steamed Rice', servings: 3, ingredients: [{ itemId: 'rice', quantity: 2 }], tools: ['pot'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [] }, { id: 'boil', action: 'boil', station: 'hob', dependsOn: ['wash'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['boil'] }], outcomes: [...basicOutcomes], memoryTags: ['staple'] },
  { id: 'simple_sabzi', displayName: 'Simple Sabzi', servings: 3, ingredients: [{ itemId: 'vegetables', quantity: 2 }, { itemId: 'potato', quantity: 1 }, { itemId: 'spices', quantity: 1 }, { itemId: 'oil', quantity: 1 }], tools: ['pan','knife'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [] }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: ['wash'] }, { id: 'fry', action: 'fry', station: 'hob', dependsOn: ['cut'] }, { id: 'stir', action: 'stir', station: 'hob', dependsOn: ['fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['home_meal'] },
  { id: 'pasta', displayName: 'Tomato Pasta', servings: 2, ingredients: [{ itemId: 'pasta', quantity: 2 }, { itemId: 'tomato', quantity: 2 }, { itemId: 'oil', quantity: 1 }], tools: ['pot','pan','knife'], steps: [{ id: 'boil', action: 'boil', station: 'hob_a', dependsOn: [] }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: [] }, { id: 'fry', action: 'fry', station: 'hob_b', dependsOn: ['cut'] }, { id: 'stir', action: 'stir', station: 'hob_b', dependsOn: ['boil','fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['shared_meal'] },
  { id: 'sandwiches', displayName: 'Vegetable Sandwiches', servings: 2, ingredients: [{ itemId: 'bread', quantity: 2 }, { itemId: 'vegetables', quantity: 1 }, { itemId: 'butter', quantity: 1, optional: true }], tools: ['knife'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [] }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: ['wash'] }, { id: 'plate', action: 'plate', station: 'counter', dependsOn: ['cut'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['plate'] }], outcomes: [...basicOutcomes], memoryTags: ['quick_meal','picnic'] },
  { id: 'noodles', displayName: 'Vegetable Noodles', servings: 2, ingredients: [{ itemId: 'noodles', quantity: 2 }, { itemId: 'vegetables', quantity: 1 }, { itemId: 'oil', quantity: 1 }], tools: ['wok','knife'], steps: [{ id: 'boil', action: 'boil', station: 'hob_a', dependsOn: [] }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: [] }, { id: 'fry', action: 'fry', station: 'hob_b', dependsOn: ['cut'] }, { id: 'stir', action: 'stir', station: 'hob_b', dependsOn: ['boil','fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['late_night','shared_meal'] },
  { id: 'pancakes', displayName: 'Pancakes', servings: 2, ingredients: [{ itemId: 'flour', quantity: 2 }, { itemId: 'milk', quantity: 1 }, { itemId: 'eggs', quantity: 1 }, { itemId: 'sugar', quantity: 1, optional: true }], tools: ['bowl','pan'], steps: [{ id: 'measure', action: 'measure', station: 'counter', dependsOn: [] }, { id: 'stir', action: 'stir', station: 'counter', dependsOn: ['measure'] }, { id: 'fry', action: 'fry', station: 'hob', dependsOn: ['stir'] }, { id: 'plate', action: 'plate', station: 'counter', dependsOn: ['fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['plate'] }], outcomes: [...basicOutcomes], memoryTags: ['breakfast','weekend'] },
  { id: 'soup', displayName: 'Vegetable Soup', servings: 3, ingredients: [{ itemId: 'vegetables', quantity: 2 }, { itemId: 'tomato', quantity: 1 }, { itemId: 'spices', quantity: 1 }], tools: ['pot','knife'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [] }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: ['wash'] }, { id: 'boil', action: 'boil', station: 'hob', dependsOn: ['cut'] }, { id: 'stir', action: 'stir', station: 'hob', dependsOn: ['boil'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['rainy_evening','comfort_food'] },
  { id: 'cake', displayName: 'Simple Home Cake', servings: 6, ingredients: [{ itemId: 'flour', quantity: 2 }, { itemId: 'milk', quantity: 1 }, { itemId: 'eggs', quantity: 2 }, { itemId: 'sugar', quantity: 2 }, { itemId: 'butter', quantity: 1 }], tools: ['bowl','oven'], steps: [{ id: 'measure', action: 'measure', station: 'counter', dependsOn: [] }, { id: 'stir', action: 'stir', station: 'counter', dependsOn: ['measure'] }, { id: 'boil', action: 'boil', station: 'oven', dependsOn: ['stir'] }, { id: 'plate', action: 'plate', station: 'counter', dependsOn: ['boil'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['plate'] }], outcomes: [...basicOutcomes], memoryTags: ['birthday','baking'] },
  { id: 'home_biscuits', displayName: 'Simple Biscuits', servings: 6, ingredients: [{ itemId: 'flour', quantity: 2 }, { itemId: 'sugar', quantity: 1 }, { itemId: 'butter', quantity: 1 }], tools: ['bowl','oven'], steps: [{ id: 'measure', action: 'measure', station: 'counter', dependsOn: [] }, { id: 'stir', action: 'stir', station: 'counter', dependsOn: ['measure'] }, { id: 'boil', action: 'boil', station: 'oven', dependsOn: ['stir'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['boil'] }], outcomes: [...basicOutcomes], memoryTags: ['baking','tea_time'] },
  { id: 'simple_curry', displayName: 'Simple Curry', servings: 3, ingredients: [{ itemId: 'vegetables', quantity: 2 }, { itemId: 'tomato', quantity: 1 }, { itemId: 'spices', quantity: 1 }, { itemId: 'oil', quantity: 1 }], tools: ['pot','knife'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [] }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: ['wash'] }, { id: 'fry', action: 'fry', station: 'hob', dependsOn: ['cut'] }, { id: 'stir', action: 'stir', station: 'hob', dependsOn: ['fry'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['stir'] }], outcomes: [...basicOutcomes], memoryTags: ['home_meal'] },
  { id: 'fruit_bowl', displayName: 'Fruit Bowl', servings: 2, ingredients: [{ itemId: 'fruit', quantity: 2 }, { itemId: 'sugar', quantity: 1, optional: true }], tools: ['bowl','knife'], steps: [{ id: 'wash', action: 'wash', station: 'sink', dependsOn: [] }, { id: 'cut', action: 'cut', station: 'counter', dependsOn: ['wash'] }, { id: 'plate', action: 'plate', station: 'counter', dependsOn: ['cut'] }, { id: 'serve', action: 'serve', station: 'table', dependsOn: ['plate'] }], outcomes: [...basicOutcomes], memoryTags: ['snack','picnic'] },
] as const;

export const activities: readonly LeisureActivityDefinition[] = [
  { id: 'picnic', displayName: 'Picnic', district: 'mogra_park', locationId: 'park_picnic_lawn', participants: [1,6], memoryTags: ['picnic','shared_food'] },
  { id: 'cycling', displayName: 'Cycling', district: 'bay_steps', locationId: 'bay_cycle_route', participants: [1,6], requiredCapability: 'bicycle', memoryTags: ['cycling','outing'] },
  { id: 'kayak', displayName: 'Kayak', district: 'bay_steps', locationId: 'bay_kayak_hut', participants: [1,2], requiredCapability: 'kayak_safety_intro', memoryTags: ['first_kayak','waterfront'] },
  { id: 'badminton', displayName: 'Badminton', district: 'mogra_park', locationId: 'park_badminton', participants: [1,4], memoryTags: ['badminton','play'] },
  { id: 'mini_golf', displayName: 'Mini-golf', district: 'hill_garden', locationId: 'hill_minigolf', participants: [1,6], memoryTags: ['mini_golf','play'] },
  { id: 'cafe_hangout', displayName: 'Café Hangout', district: 'lantern_street', locationId: 'lantern_cafe_roshan', participants: [1,6], memoryTags: ['cafe','quiet_time'] },
  { id: 'board_game', displayName: 'Board / Card Game', district: 'mogra_court', locationId: 'home_table', participants: [2,6], memoryTags: ['game_night','home'] },
  { id: 'photography', displayName: 'Photography', district: 'all', locationId: 'city', participants: [1,6], memoryTags: ['photo','exploration'] },
] as const;

export const storyEvents: readonly StoryDefinition[] = [
  { id: 'move_in_day', title: 'Move-In Day', paths: ['all'], stageRange: [0,0], triggers: [{ type: 'flag', key: 'property_assigned', value: true }], tasks: [{ id: 'enter', type: 'location', target: 'home' }, { id: 'box', type: 'micro_action', target: 'place_box' }, { id: 'photo', type: 'photo', target: 'first_home' }], outcomes: [{ id: 'settled', when: { maxFailures: 0 }, memoryTag: 'move_in' }, { id: 'messy_start', when: { minFailures: 1 }, memoryTag: 'move_in_chaos' }] },
  { id: 'first_dinner', title: 'First Dinner', paths: ['all'], stageRange: [0,1], triggers: [{ type: 'flag', key: 'moved_in', value: true }], tasks: [{ id: 'groceries', type: 'purchase', target: 'groceries' }, { id: 'cook', type: 'micro_action', target: 'cook_meal' }, { id: 'eat', type: 'interaction', target: 'shared_meal' }], outcomes: [{ id: 'warm', when: { maxFailures: 1 }, memoryTag: 'first_dinner' }, { id: 'burnt', when: { minFailures: 2 }, memoryTag: 'burned_first_dinner' }] },
  { id: 'pipe_disaster', title: 'The Great Pipe Disaster', paths: ['all'], stageRange: [1,3], triggers: [{ type: 'flag', key: 'first_chore_cycle', value: true }], tasks: [{ id: 'inspect', type: 'interaction', target: 'leaking_pipe' }, { id: 'repair', type: 'micro_action', target: 'repair_pipe' }], outcomes: [{ id: 'fixed', when: { maxFailures: 1 }, memoryTag: 'pipe_fixed' }, { id: 'call_ravi', when: { minFailures: 2 }, memoryTag: 'ravi_rescue' }] },
  { id: 'quiet_anniversary', title: 'A Quiet Anniversary', paths: ['couple'], stageRange: [2,6], triggers: [{ type: 'flag', key: 'anniversary_ready', value: true }], tasks: [{ id: 'choose', type: 'choice', target: 'anniversary_plan' }, { id: 'photo', type: 'photo', target: 'anniversary' }], outcomes: [{ id: 'quiet', when: { maxFailures: 0 }, memoryTag: 'quiet_anniversary' }, { id: 'improvised', when: { minFailures: 1 }, memoryTag: 'anniversary_improvised' }] },
  { id: 'leftovers', title: 'Somebody Ate My Leftovers', paths: ['friends'], stageRange: [1,4], triggers: [{ type: 'flag', key: 'shared_fridge_active', value: true }], tasks: [{ id: 'talk', type: 'choice', target: 'leftovers_response' }], outcomes: [{ id: 'laugh', when: { maxFailures: 0 }, memoryTag: 'leftovers_joke' }, { id: 'label_fridge', when: { minFailures: 1 }, memoryTag: 'fridge_labels' }] },
  { id: 'monsoon_leak', title: 'Monsoon Leak', paths: ['all'], stageRange: [2,5], triggers: [{ type: 'flag', key: 'monsoon_active', value: true }], tasks: [{ id: 'bucket', type: 'interaction', target: 'place_bucket' }, { id: 'wipe', type: 'micro_action', target: 'wipe_floor' }], outcomes: [{ id: 'contained', when: { maxFailures: 1 }, memoryTag: 'monsoon_home' }, { id: 'soggy', when: { minFailures: 2 }, memoryTag: 'soggy_evening' }] },
  { id: 'first_kayak', title: 'First Kayak Day', paths: ['all'], stageRange: [1,6], triggers: [{ type: 'flag', key: 'kayak_intro_complete', value: true }], tasks: [{ id: 'visit', type: 'location', target: 'bay_kayak_hut' }, { id: 'photo', type: 'photo', target: 'kayak' }], outcomes: [{ id: 'smooth', when: { maxFailures: 1 }, memoryTag: 'first_kayak' }, { id: 'splashy', when: { minFailures: 2 }, memoryTag: 'kayak_splash' }] },
  { id: 'flat_pack', title: 'The Flat-Pack Problem', paths: ['all'], stageRange: [1,4], triggers: [{ type: 'flag', key: 'bought_flat_pack', value: true }], tasks: [{ id: 'assemble', type: 'micro_action', target: 'assemble_furniture' }], outcomes: [{ id: 'straight', when: { maxFailures: 1 }, memoryTag: 'flat_pack_win' }, { id: 'wobbly', when: { minFailures: 2 }, memoryTag: 'wobbly_furniture' }] },
  { id: 'power_cut', title: 'The Power Cut', paths: ['all'], stageRange: [1,4], triggers: [{ type: 'flag', key: 'first_days_active', value: true }], tasks: [{ id: 'lights', type: 'interaction', target: 'find_torch' }, { id: 'sit', type: 'interaction', target: 'sit_together' }], outcomes: [{ id: 'candles', when: { maxFailures: 0 }, memoryTag: 'power_cut_candles' }, { id: 'dark_laugh', when: { minFailures: 1 }, memoryTag: 'power_cut_laugh' }] },
  { id: 'new_neighbour', title: 'New Neighbour', paths: ['all'], stageRange: [1,3], triggers: [{ type: 'flag', key: 'moved_in', value: true }], tasks: [{ id: 'door', type: 'interaction', target: 'front_door' }, { id: 'talk', type: 'interaction', target: 'kabir' }], outcomes: [{ id: 'welcome', when: { maxFailures: 0 }, memoryTag: 'new_neighbour' }, { id: 'awkward', when: { minFailures: 1 }, memoryTag: 'awkward_neighbour' }] },
  { id: 'adopt_plant', title: 'Adopt a Plant', paths: ['all'], stageRange: [1,4], triggers: [{ type: 'flag', key: 'met_naina', value: true }], tasks: [{ id: 'visit', type: 'location', target: 'rain_tree_nursery' }, { id: 'buy', type: 'purchase', target: 'plant' }, { id: 'water', type: 'micro_action', target: 'water_plant' }], outcomes: [{ id: 'pothos', when: { maxFailures: 0 }, memoryTag: 'plant_adopted' }, { id: 'crooked_pot', when: { minFailures: 1 }, memoryTag: 'crooked_plant' }] },
  { id: 'freelance_deadline', title: 'The Freelance Deadline', paths: ['all'], stageRange: [2,5], triggers: [{ type: 'flag', key: 'freelance_unlocked', value: true }], tasks: [{ id: 'work', type: 'interaction', target: 'freelance_desk' }, { id: 'choice', type: 'choice', target: 'take_break' }], outcomes: [{ id: 'balanced', when: { maxFailures: 1 }, memoryTag: 'deadline_done' }, { id: 'late_night', when: { minFailures: 2 }, memoryTag: 'deadline_late' }] },
  { id: 'stuck_indoors', title: 'Stuck Indoors', paths: ['all'], stageRange: [1,5], triggers: [{ type: 'flag', key: 'monsoon_active', value: true }], tasks: [{ id: 'window', type: 'interaction', target: 'rainy_window' }, { id: 'activity', type: 'choice', target: 'indoor_activity' }], outcomes: [{ id: 'cozy', when: { maxFailures: 0 }, memoryTag: 'rainy_day_home' }, { id: 'restless', when: { minFailures: 1 }, memoryTag: 'rainy_day_restless' }] },
  { id: 'job_good_news', title: 'Job Good News', paths: ['all'], stageRange: [2,5], triggers: [{ type: 'flag', key: 'job_trust_ready', value: true }], tasks: [{ id: 'talk', type: 'interaction', target: 'job_mentor' }, { id: 'share', type: 'choice', target: 'share_good_news' }], outcomes: [{ id: 'celebrate', when: { maxFailures: 0 }, memoryTag: 'job_good_news' }, { id: 'quiet_pride', when: { minFailures: 1 }, memoryTag: 'quiet_job_win' }] },
  { id: 'housemate_birthday', title: 'Housemate Birthday', paths: ['friends'], stageRange: [2,6], triggers: [{ type: 'flag', key: 'birthday_ready', value: true }], tasks: [{ id: 'cake', type: 'micro_action', target: 'cook_cake' }, { id: 'photo', type: 'photo', target: 'birthday' }], outcomes: [{ id: 'surprise', when: { maxFailures: 1 }, memoryTag: 'housemate_birthday' }, { id: 'collapsed_cake', when: { minFailures: 2 }, memoryTag: 'birthday_cake_fail' }] },
  { id: 'something_needs_said', title: 'Something Needs to Be Said', paths: ['couple'], stageRange: [3,6], triggers: [{ type: 'flag', key: 'tension_ready', value: true }], tasks: [{ id: 'sit', type: 'interaction', target: 'quiet_seat' }, { id: 'choice', type: 'choice', target: 'difficult_conversation' }], outcomes: [{ id: 'repair', when: { maxFailures: 1 }, memoryTag: 'talked_it_out' }, { id: 'pause', when: { minFailures: 2 }, memoryTag: 'needed_more_time' }] },
  { id: 'block_evening', title: 'Block Evening / Street Gathering', paths: ['all'], stageRange: [2,6], triggers: [{ type: 'flag', key: 'community_intro', value: true }], tasks: [{ id: 'visit', type: 'location', target: 'common_event_square' }, { id: 'help', type: 'interaction', target: 'community_setup' }, { id: 'photo', type: 'photo', target: 'block_evening' }], outcomes: [{ id: 'joined', when: { maxFailures: 1 }, memoryTag: 'block_evening' }, { id: 'late', when: { minFailures: 2 }, memoryTag: 'late_to_block_evening' }] },
  { id: 'expensive_thing', title: 'The Expensive Thing We Bought', paths: ['all'], stageRange: [2,6], triggers: [{ type: 'flag', key: 'major_purchase_done', value: true }], tasks: [{ id: 'place', type: 'interaction', target: 'new_purchase' }, { id: 'photo', type: 'photo', target: 'expensive_purchase' }], outcomes: [{ id: 'worth_it', when: { maxFailures: 0 }, memoryTag: 'big_purchase' }, { id: 'buyers_remorse', when: { minFailures: 1 }, memoryTag: 'maybe_too_expensive' }] },
  { id: 'moving_day', title: 'Moving Day', paths: ['all'], stageRange: [4,6], triggers: [{ type: 'flag', key: 'move_ready', value: true }], tasks: [{ id: 'pack', type: 'micro_action', target: 'pack_boxes' }, { id: 'vote', type: 'vote', target: 'moving_confirm' }, { id: 'photo', type: 'photo', target: 'old_home_final' }], outcomes: [{ id: 'packed', when: { maxFailures: 1 }, memoryTag: 'moving_day' }, { id: 'broken_mug', when: { minFailures: 2 }, memoryTag: 'moving_broken_mug' }] },
  { id: 'first_night_new_place', title: 'First Night in the New Place', paths: ['all'], stageRange: [4,6], triggers: [{ type: 'flag', key: 'moved_home', value: true }], tasks: [{ id: 'box', type: 'micro_action', target: 'unpack_first_box' }, { id: 'meal', type: 'interaction', target: 'first_new_home_meal' }, { id: 'photo', type: 'photo', target: 'first_new_home_night' }], outcomes: [{ id: 'settled', when: { maxFailures: 1 }, memoryTag: 'new_home_first_night' }, { id: 'floor_picnic', when: { minFailures: 2 }, memoryTag: 'new_home_floor_picnic' }] },

  { id: 'first_festival_lights', title: 'Lights Across the Lane', paths: ['all'], stageRange: [2,6], triggers: [], tasks: [{ id: 'walk', type: 'location', target: 'lantern_street' }, { id: 'help', type: 'interaction', target: 'festival_lights' }, { id: 'photo', type: 'photo', target: 'festival_evening' }], outcomes: [{ id: 'glowing_lane', when: { maxFailures: 1 }, memoryTag: 'festival_lights' }, { id: 'tangled_lights', when: { minFailures: 2 }, memoryTag: 'festival_lights_tangle' }] },
  { id: 'rainy_balcony_evening', title: 'Rain on the Balcony', paths: ['all'], stageRange: [1,6], triggers: [], tasks: [{ id: 'drink', type: 'interaction', target: 'make_hot_drink' }, { id: 'sit', type: 'interaction', target: 'balcony_sit' }], outcomes: [{ id: 'quiet_rain', when: { maxFailures: 0 }, memoryTag: 'balcony_rain' }, { id: 'inside_instead', when: { minFailures: 1 }, memoryTag: 'rainy_window' }] },
  { id: 'cafe_regular', title: 'Roshan Knows the Order', paths: ['all'], stageRange: [2,6], triggers: [{ type: 'flag', key: 'job_trust_ready', value: true }], tasks: [{ id: 'visit', type: 'location', target: 'lantern_cafe_roshan' }, { id: 'talk', type: 'interaction', target: 'roshan' }], outcomes: [{ id: 'usual', when: { maxFailures: 0 }, memoryTag: 'cafe_regular' }, { id: 'try_something_new', when: { minFailures: 1 }, memoryTag: 'cafe_new_order' }] },
  { id: 'library_slow_day', title: 'A Slow Afternoon at the Common', paths: ['all'], stageRange: [2,6], triggers: [], tasks: [{ id: 'visit', type: 'location', target: 'common_library' }, { id: 'read', type: 'interaction', target: 'library_reading' }, { id: 'note', type: 'choice', target: 'leave_book_note' }], outcomes: [{ id: 'quiet_afternoon', when: { maxFailures: 1 }, memoryTag: 'library_afternoon' }, { id: 'lost_track_time', when: { minFailures: 2 }, memoryTag: 'library_late' }] },

  { id: 'quiet_date', title: 'No Plan, Just a Date', paths: ['couple'], stageRange: [1,6], triggers: [], tasks: [{ id: 'choose', type: 'choice', target: 'date_place' }, { id: 'visit', type: 'location', target: 'bay_steps' }, { id: 'photo', type: 'photo', target: 'quiet_date' }], outcomes: [{ id: 'unhurried', when: { maxFailures: 1 }, memoryTag: 'quiet_date' }, { id: 'changed_plans', when: { minFailures: 2 }, memoryTag: 'date_changed_plans' }] },
  { id: 'surprise_meal', title: 'I Made Something for Us', paths: ['couple'], stageRange: [2,6], triggers: [], tasks: [{ id: 'groceries', type: 'purchase', target: 'meal_ingredients' }, { id: 'cook', type: 'micro_action', target: 'surprise_meal' }, { id: 'serve', type: 'interaction', target: 'serve_partner' }], outcomes: [{ id: 'warm_plate', when: { maxFailures: 1 }, memoryTag: 'surprise_meal' }, { id: 'takeout_backup', when: { minFailures: 2 }, memoryTag: 'surprise_meal_backup' }] },
  { id: 'weekend_bay_evening', title: 'Weekend by the Bay', paths: ['couple'], stageRange: [2,6], triggers: [], tasks: [{ id: 'ride', type: 'location', target: 'bay_steps' }, { id: 'sit', type: 'interaction', target: 'sunset_lookout' }, { id: 'photo', type: 'photo', target: 'bay_evening' }], outcomes: [{ id: 'sunset', when: { maxFailures: 0 }, memoryTag: 'weekend_bay' }, { id: 'cloudy', when: { minFailures: 1 }, memoryTag: 'weekend_bay_clouds' }] },
  { id: 'shared_purchase_talk', title: 'Do We Really Need It?', paths: ['couple'], stageRange: [2,6], triggers: [], tasks: [{ id: 'browse', type: 'location', target: 'furniture_shop' }, { id: 'choose', type: 'choice', target: 'shared_purchase' }], outcomes: [{ id: 'together_yes', when: { maxFailures: 0 }, memoryTag: 'shared_purchase_yes' }, { id: 'walked_away', when: { minFailures: 1 }, memoryTag: 'shared_purchase_no' }] },
  { id: 'first_festival_together', title: 'Our First Festival Here', paths: ['couple'], stageRange: [3,6], triggers: [], tasks: [{ id: 'decorate', type: 'interaction', target: 'home_lights' }, { id: 'meal', type: 'micro_action', target: 'festival_meal' }, { id: 'photo', type: 'photo', target: 'festival_home' }], outcomes: [{ id: 'home_glow', when: { maxFailures: 1 }, memoryTag: 'first_festival_together' }, { id: 'improvised_glow', when: { minFailures: 2 }, memoryTag: 'festival_improvised' }] },
  { id: 'sunday_morning', title: 'A Very Slow Sunday', paths: ['couple'], stageRange: [2,6], triggers: [], tasks: [{ id: 'coffee', type: 'micro_action', target: 'morning_coffee' }, { id: 'sit', type: 'interaction', target: 'home_sofa' }, { id: 'choice', type: 'choice', target: 'what_next' }], outcomes: [{ id: 'stayed_in', when: { maxFailures: 0 }, memoryTag: 'slow_sunday' }, { id: 'went_out', when: { minFailures: 1 }, memoryTag: 'sunday_walk' }] },

  { id: 'fridge_space', title: 'Whose Shelf Is This?', paths: ['friends'], stageRange: [1,6], triggers: [], tasks: [{ id: 'inspect', type: 'interaction', target: 'shared_fridge' }, { id: 'choice', type: 'choice', target: 'fridge_space' }], outcomes: [{ id: 'labels', when: { maxFailures: 0 }, memoryTag: 'fridge_shelves' }, { id: 'chaos', when: { minFailures: 1 }, memoryTag: 'fridge_chaos' }] },
  { id: 'late_night_game', title: 'One More Round', paths: ['friends'], stageRange: [1,6], triggers: [], tasks: [{ id: 'sit', type: 'interaction', target: 'shared_table' }, { id: 'play', type: 'interaction', target: 'board_game' }], outcomes: [{ id: 'last_round', when: { maxFailures: 0 }, memoryTag: 'late_night_game' }, { id: 'way_too_late', when: { minFailures: 1 }, memoryTag: 'game_night_too_late' }] },
  { id: 'contribution_talk', title: 'Who Keeps Buying the Milk?', paths: ['friends'], stageRange: [2,6], triggers: [], tasks: [{ id: 'board', type: 'interaction', target: 'household_board' }, { id: 'talk', type: 'choice', target: 'contribution_balance' }], outcomes: [{ id: 'fair_plan', when: { maxFailures: 1 }, memoryTag: 'contribution_plan' }, { id: 'joke_chart', when: { minFailures: 2 }, memoryTag: 'contribution_joke' }] },
  { id: 'pg_inspection', title: 'The PG Inspection', paths: ['friends'], stageRange: [2,5], triggers: [], tasks: [{ id: 'tidy', type: 'micro_action', target: 'common_room_clean' }, { id: 'trash', type: 'micro_action', target: 'take_trash' }, { id: 'door', type: 'interaction', target: 'front_door' }], outcomes: [{ id: 'fine', when: { maxFailures: 1 }, memoryTag: 'pg_inspection' }, { id: 'hidden_laundry', when: { minFailures: 2 }, memoryTag: 'pg_inspection_laundry' }] },
  { id: 'group_picnic', title: 'Everybody Bring Something', paths: ['friends'], stageRange: [2,6], triggers: [], tasks: [{ id: 'food', type: 'purchase', target: 'picnic_food' }, { id: 'visit', type: 'location', target: 'mogra_park' }, { id: 'photo', type: 'photo', target: 'group_picnic' }], outcomes: [{ id: 'full_mat', when: { maxFailures: 1 }, memoryTag: 'friends_picnic' }, { id: 'forgot_cups', when: { minFailures: 2 }, memoryTag: 'picnic_no_cups' }] },
  { id: 'bigger_shared_place', title: 'Maybe We Need More Room', paths: ['friends'], stageRange: [3,6], triggers: [], tasks: [{ id: 'visit', type: 'location', target: 'property_visit' }, { id: 'vote', type: 'vote', target: 'bigger_home' }], outcomes: [{ id: 'save_for_it', when: { maxFailures: 0 }, memoryTag: 'bigger_home_plan' }, { id: 'stay_cozy', when: { minFailures: 1 }, memoryTag: 'stay_in_current_home' }] },
] as const;
